### ISSUE TITLE
PA1

### ISSUE THREAD

**Issue by akimovatatiana** [karupoiss00/distributed-programming#1]
1. С какой целью вы решили использовать nginx?
2. Нет возможности запустить docker-compose без дополнительных файлов:
https://github.com/karupoiss00/distributed-programming/blob/10495cc5b2afec1b407106d9bd0a3a737ec871a0/debug/docker-compose.yml#L16
Если хотите использовать докер, необходимо предоставить все настройки для корректного запуска на новой машине

**Comment by karupoiss00** [comment]
1. Для проксирования запросов. На данном этапе большого толка от него нет, так как все запросы идут по итогу к одному экземпляру приложения.
2. Закоммитил конфиг

**Comment by akimovatatiana** [comment]
Необходимо написать метод для расчета rank, который будет проверять буквы не только из русского и английского алфавитов.   (https://learn.microsoft.com/ru-ru/dotnet/api/system.char.isletter?view=net-7.0):
https://github.com/karupoiss00/distributed-programming/blob/8aaf214eb714232f87a20ff7a7942f29ce5ce8c1/Valuator/Pages/Index.cshtml.cs#L49
https://github.com/karupoiss00/distributed-programming/blob/8aaf214eb714232f87a20ff7a7942f29ce5ce8c1/Valuator/Pages/Index.cshtml.cs#L51

**Comment by karupoiss00** [comment]
Поправил
